services:
  db:
    image: mariadb:10.4
    volumes:
      - ./shared/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    networks:
      ipvlan40:
        ipv4_address: 192.168.72.130
      ipvlan20:
        ipv4_address: 192.168.70.3
  opensearch:
      image: opensearchproject/opensearch:2.4.0
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
        - plugins.security.disabled=true
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - opensearch_data:/usr/share/opensearch/data
      networks:
        ipvlan40:
          ipv4_address: 192.168.72.131
        ipvlan20:
          ipv4_address: 192.168.70.2
        
networks:
  ipvlan40:
    external: true
    name: ipvlan40 
  ipvlan20:
    external: true
    name: ipvlan20
  ipvlan30:
    external: true
    name: ipvlan30 

volumes:
  opensearch_data: