x-logging:
  logging: &logging
    options:
      max-size: "10m"
      max-file: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "127.0.0.1:8082:80"
    environment:
      WEB_PORT: ${WEB_PORT}
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/templates/default.conf.template:ro
      - ./app:/app
    logging: *logging
