networks:
  ipvlan30:
    external: true
    name: ipvlan30 
  ipvlan40:
    external: true
    name: ipvlan40 
services:
  web:
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - redis
    environment:
      - DB_HOST=db 
      - DB_NAME=magento
      - DB_USER=magento
      - DB_PASSWORD=magento
      - REDIS_HOST=redis
    networks:
      ipvlan30:
        ipv4_address: 192.168.71.130
      ipvlan40:  

  redis:
    image: redis:alpine
    volumes:
      - ../shared/redis:/data
    networks:
      ipvlan30:
        ipv4_address: 192.168.71.131
      ipvlan40:

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      ipvlan30:
        ipv4_address: 192.168.71.132
      ipvlan40:

volumes:
  opensearch_data:
