services:
  web:
    build: ./php
    container_name: magento-web
    ports:
      - "9001:9000"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db 
      - DB_NAME=magento
      - DB_USER=magento
      - DB_PASSWORD=magento
      - REDIS_HOST=redis
    networks:
      - magento-network 

  db:
    image: mysql:5.7
    container_name: magento-db
    ports:
      - "3307:3307"
    volumes:
      - ../shared/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    networks:
      - magento-network

  redis:
    image: redis:alpine
    volumes:
      - ../shared/redis:/data
    networks:
      - magento-network

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - magento-network

volumes:
  opensearch_data:

networks:
  magento-network: 
    driver: bridge
    name: magento-network