networks:
  ipvlan20:
    external: true
    name: ipvlan20
services:
  web:
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - redis
    environment:
      - DB_NAME=magento
      - DB_USER=magento
      - DB_PASSWORD=magento
      - REDIS_HOST=redis
    networks:
      ipvlan20:
        ipv4_address: 192.168.70.4

  redis:
    image: redis:alpine
    volumes:
      - ../shared/redis:/data
    networks:
      ipvlan20:
        ipv4_address: 192.168.70.5